### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by womanonrails** [kasiaekiert/mapsapp#20]
https://github.com/kasiaekiert/mapsapp/blob/10fa5181f5a101f8c775fba5942cf695e5239b22/app/controllers/application_controller.rb#L15

**Comment by kasiaekiert** [comment]
done

**Comment by womanonrails** [comment]
Where can I find it? Can you provide a link?

**Comment by kasiaekiert** [comment]
https://github.com/kasiaekiert/mapsapp/blob/develop/app/controllers/application_controller.rb

**Comment by womanonrails** [comment]
As we already discussed it before. You can only use `<%= ` in views. So `redirect_to root_url, :alert => "<%= t('.no_access')%>"` shouldn't have this `<%= `

**Comment by kasiaekiert** [comment]
redirect_to root_url, :alert => "t('.no_access')"

?

**Comment by womanonrails** [comment]
Just `redirect_to root_url, alert:  t('.no_access')`
