### ISSUE TITLE
This value should be in plural so it should be `@places` 

### ISSUE THREAD

**Issue by womanonrails** [kasiaekiert/mapsapp#21]
https://github.com/kasiaekiert/mapsapp/blob/10fa5181f5a101f8c775fba5942cf695e5239b22/app/controllers/events_controller.rb#L56

**Comment by kasiaekiert** [comment]
We don`t need it probably now... We deleted set_place method

**Comment by womanonrails** [comment]
If this line doesn't exist any more, you can close this issue.
