### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by womanonrails** [kasiaekiert/mapsapp#22]
https://github.com/kasiaekiert/mapsapp/blob/10fa5181f5a101f8c775fba5942cf695e5239b22/app/controllers/settings_controller.rb#L7

**Comment by kasiaekiert** [comment]
Zrobiłam coś takiego: 
W setting controller
format.html { redirect_to profile_path, notice: "<%= t('.setting_updated')%>" }

i w jezykowych: 
controller: 
    application-controller:
      alert: 'You have no access here'
    setting_controller:
      flash_message:
        alert-info: Your setting was successfully updated.

albo wersja bez flash message.... ale nie dziala.. :(
